# Generated by Django 5.2.11 on 2026-02-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_savedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplace',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
