# Generated by Django 5.2.11 on 2026-03-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_savedplace_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplace',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='savedplace',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
