# Generated by Django 5.2.13 on 2026-04-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_savedplace_average_visit_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplace',
            name='is_check_it_out',
            field=models.BooleanField(default=False),
        ),
    ]
