# Generated by Django 5.2.11 on 2026-04-21 18:04

from django.db import migrations
from django.contrib.gis.geos import Point

def migrate_lat_lng(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        if place.latitude is not None and place.longitude is not None:
            place.location = Point(place.longitude, place.latitude, srid=4326)
            place.save()

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_location'),
    ]

    operations = [
        migrations.RunPython(migrate_lat_lng),
    ]
